"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const required = ["index.html", "styles.css", "core.js", "app.js", "manifest.json", "service-worker.js", "icon-192.png", "icon-512.png", "favicon.png"];
for (const file of required) assert.ok(fs.existsSync(path.join(root, file)), `${file} missing`);
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
for (const ref of ["styles.css", "core.js", "app.js", "manifest.json"]) assert.ok(html.includes(ref), `${ref} not linked`);
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
for (const phrase of ["Pause shift", "Resume shift", "Finish & show money plan", "Bitcoin", "Solana", "Ethereum", "AAVE"]) assert.ok(app.includes(phrase), `${phrase} not found`);
console.log("static.test.js: all assertions passed");
